%YAML:1.0
R: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1.5488958003483515e-04, -5.7734502585365222e-01,
       8.1650027380966850e-01, 5.7742609881875062e-01,
       6.6667753729449497e-01, 4.7129625679598330e-01,
       -8.1644294130831718e-01, 4.7139556891107148e-01,
       3.3347734735485529e-01 ]
T: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -2.8276828737707518e+01, -1.6323873185359236e+01,
       2.3086033120560462e+01 ]
R1: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 7.0718417352120877e-01, -4.0826048124681175e-01,
       5.7724684856068842e-01, 4.0827140140417778e-01,
       9.0236491076515069e-01, 1.3802909336538516e-01,
       -5.7723912507434338e-01, 1.3806138950453589e-01,
       8.0481926245057245e-01 ]
R2: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 7.0713890346567942e-01, 4.0822278522435446e-01,
       -5.7732896067062733e-01, -4.0821186322269359e-01,
       9.0238557405400532e-01, 1.3807009257431524e-01,
       5.7733668333963784e-01, 1.3803779686337186e-01,
       8.0475332910618835e-01 ]
P1: !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [ 9.6868092985666556e+02, 0., -5.2133222961425781e+02, 0., 0.,
       9.6868092985666556e+02, 7.0918803393840790e+01, 0., 0., 0., 1.,
       0. ]
P2: !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [ 9.6868092985666556e+02, 0., 1.0318872833251953e+03,
       -3.8735281881418166e+04, 0., 9.6868092985666556e+02,
       7.0918803393840790e+01, 0., 0., 0., 1., 0. ]
Q: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 1., 0., 0., 5.2133222961425781e+02, 0., 1., 0.,
       -7.0918803393840790e+01, 0., 0., 0., 9.6868092985666556e+02, 0.,
       0., 2.5007716035786869e-02, 3.8842472520833034e+01 ]
