%YAML:1.0
M1: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 9.6855363970456017e+02, 0., 2.5549902308171781e+02, 0.,
       9.6868092985666556e+02, 2.5550060896358323e+02, 0., 0., 1. ]
D1: !!opencv-matrix
   rows: 1
   cols: 14
   dt: d
   data: [ 1.3149784035809700e-02, -1.0856322266980787e+00, 0., 0., 0.,
       0., 0., 2.2440025300842846e-02, 0., 0., 0., 0., 0., 0. ]
M2: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 9.6855363970456017e+02, 0., 2.5550132931209308e+02, 0.,
       9.6868092985666556e+02, 2.5550139910018541e+02, 0., 0., 1. ]
D2: !!opencv-matrix
   rows: 1
   cols: 14
   dt: d
   data: [ 1.6868928456528917e-02, -9.5311519495992802e-01, 0., 0., 0.,
       0., 0., 2.0889722538675486e-02, 0., 0., 0., 0., 0., 0. ]
