%YAML:1.0
A1: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 4.7044376140907189e+03, 0., 1.2387206678856410e+03, 0.,
       4.7691463862436294e+03, 1.0245150821018608e+03, 0., 0., 1. ]
A2: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 4.7557605106307119e+03, 0., 1.3091988330046227e+03, 0.,
       4.8009624659403844e+03, 9.8241777489902154e+02, 0., 0., 1. ]
D1: !!opencv-matrix
   rows: 5
   cols: 1
   dt: d
   data: [ -5.3637301247422706e-02, -2.5903723278328212e+00,
       -8.7588679104234068e-03, 4.6142149059182194e-04,
       2.2321178694957204e+01 ]
D2: !!opencv-matrix
   rows: 5
   cols: 1
   dt: d
   data: [ -2.1636004418787122e-01, 2.6862611288769727e+00,
       -7.8852605838023587e-03, 3.2475527370491417e-03,
       -3.0559805916682162e+01 ]
R: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 7.2809011190165662e-01, -5.0981928116460606e-01,
       4.5822384213813844e-01, 4.1086749966172342e-01,
       8.5965656604483320e-01, 3.0360910094680826e-01,
       -5.4870090821207584e-01, -3.2785499978037702e-02,
       8.3537561870001520e-01 ]
T: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -2.7353924090294140e+02, -1.3798336261040697e+02,
       1.9465332385841754e+02 ]
R1: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 9.9912538459829503e-01, -3.9824640209576073e-02,
       1.2746132099064722e-02, 3.8386247429067599e-02,
       9.9443605436902982e-01, 9.8099081439483690e-02,
       -1.6581973936277583e-02, -9.7524006291445337e-02,
       9.9509502377272641e-01 ]
R2: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 7.5359726414307715e-01, 3.8014247687907038e-01,
       -5.3626752721781945e-01, -4.3408268920904886e-01,
       9.0042891907217970e-01, 2.8283928785553254e-02,
       4.9362271261066337e-01, 2.1146975899818737e-01,
       8.4357403861435842e-01 ]
P1: !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [ 4.6861906094293963e+03, 0., 1.1745923767089844e+03, 0., 0.,
       4.6861906094293963e+03, 6.1312707138061523e+02, 0., 0., 0., 1.,
       0. ]
P2: !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [ 4.6861906094293963e+03, 0., 4.6178750610351563e+03, 0., 0.,
       4.6861906094293963e+03, 6.1312707138061523e+02, 0., 0., 0., 1.,
       0. ]
Q: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 1., 0., 0., -1.1745923767089844e+03, 0., 1., 0.,
       -6.1312707138061523e+02, 0., 0., 0., 4.6861906094293963e+03, 0.,
       0., 2.7549877730722828e-03, 9.4862016945501111e+00 ]
