%YAML:1.0
A1: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 4.7044376140907189e+03, 0., 1.2387206678856410e+03, 0.,
       4.7691463862436294e+03, 1.0245150821018608e+03, 0., 0., 1. ]
A2: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 4.7557605106307119e+03, 0., 1.3091988330046227e+03, 0.,
       4.8009624659403844e+03, 9.8241777489902154e+02, 0., 0., 1. ]
D1: !!opencv-matrix
   rows: 5
   cols: 1
   dt: d
   data: [ -5.3637301247422706e-02, -2.5903723278328212e+00,
       -8.7588679104234068e-03, 4.6142149059182194e-04,
       2.2321178694957204e+01 ]
D2: !!opencv-matrix
   rows: 5
   cols: 1
   dt: d
   data: [ -2.1636004418787122e-01, 2.6862611288769727e+00,
       -7.8852605838023587e-03, 3.2475527370491417e-03,
       -3.0559805916682162e+01 ]
R: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 7.2893057379093129e-01, -5.0828097792337856e-01,
       4.5859640870167945e-01, 4.0889153069325318e-01,
       8.6052178303663385e-01, 3.0382557010031419e-01,
       -5.4906095719888171e-01, -3.3951559621120453e-02,
       8.3509242415384266e-01 ]
T: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -2.7418252214488501e+02, -1.3798791135909286e+02,
       1.9448185597240416e+02 ]
R1: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 9.9915112242325432e-01, -3.8575227110170453e-02,
       1.4456362396878919e-02, 3.6976052006677584e-02,
       9.9449036240738609e-01, 9.8090216927200616e-02,
       -1.8160565474417245e-02, -9.7472411133738640e-02,
       9.9507252144224378e-01 ]
R2: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 7.5454849100910826e-01, 3.7974182117444794e-01,
       -5.3521278382246362e-01, -4.3354373792246759e-01,
       9.0070213045472591e-01, 2.7847791699386188e-02,
       4.9264226577110937e-01, 2.1102564167757273e-01,
       8.4425812198075778e-01 ]
P1: !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [ 4.6861906094293963e+03, 0., 1.1659838562011719e+03, 0., 0.,
       4.6861906094293963e+03, 6.1470760345458984e+02, 0., 0., 0., 1.,
       0. ]
P2: !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [ 4.6861906094293963e+03, 0., 4.6080891418457031e+03, 0., 0.,
       4.6861906094293963e+03, 6.1470760345458984e+02, 0., 0., 0., 1.,
       0. ]
Q: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 1., 0., 0., -1.1659838562011719e+03, 0., 1., 0.,
       -6.1470760345458984e+02, 0., 0., 0., 4.6861906094293963e+03, 0.,
       0., 2.7519933988001811e-03, 9.4726510240689628e+00 ]
