%YAML:1.0
M1: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 4.7044376140907189e+03, 0., 1.2387206678856410e+03, 0.,
       4.7691463862436294e+03, 1.0245150821018608e+03, 0., 0., 1. ]
D1: !!opencv-matrix
   rows: 5
   cols: 1
   dt: d
   data: [ -5.3637301247422706e-02, -2.5903723278328212e+00,
       -8.7588679104234068e-03, 4.6142149059182194e-04,
       2.2321178694957204e+01 ]
M2: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 4.7557605106307119e+03, 0., 1.3091988330046227e+03, 0.,
       4.8009624659403844e+03, 9.8241777489902154e+02, 0., 0., 1. ]
D2: !!opencv-matrix
   rows: 5
   cols: 1
   dt: d
   data: [ -2.1636004418787122e-01, 2.6862611288769727e+00,
       -7.8852605838023587e-03, 3.2475527370491417e-03,
       -3.0559805916682162e+01 ]
