%YAML:1.0
calibration_time: "Sun Jan  6 09:56:21 2019"
R: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 6.6556978225708008e-01, -7.3706364631652832e-01,
       1.1727800220251083e-01, -3.0638778209686279e-01,
       -4.1312381625175476e-01, -8.5758697986602783e-01,
       6.8054646253585815e-01, 5.3485137224197388e-01,
       -5.0078999996185303e-01 ]
T: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -4.0126373291015625e+01, 1.9383396148681641e+01,
       6.1869726562500000e+02 ]
