%YAML:1.0
calibration_time: "Sun Jan  6 09:56:21 2019"
R: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ -8.7235895916819572e-03, -9.9996155500411987e-01,
       9.3424582155421376e-04, -6.3171762228012085e-01,
       4.7868168912827969e-03, -7.7518385648727417e-01,
       7.7514952421188354e-01, -7.3525649495422840e-03,
       -6.3173502683639526e-01 ]
T: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ 9.9513511657714844e+00, 2.0562140941619873e+00,
       5.1167779541015625e+02 ]
