%YAML:1.0
calibration_time: "Wed Dec 26 10:03:17 2018"
nframes: 35
image_width: 2448
image_height: 2048
board_width: 12
board_height: 9
square_size: 1.2510000228881836e+01
flags: 0
camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 4.7557605106307119e+03, 0., 1.3091988330046227e+03, 0.,
       4.8009624659403844e+03, 9.8241777489902154e+02, 0., 0., 1. ]
distortion_coefficients: !!opencv-matrix
   rows: 5
   cols: 1
   dt: d
   data: [ -2.1636004418787122e-01, 2.6862611288769727e+00,
       -7.8852605838023587e-03, 3.2475527370491417e-03,
       -3.0559805916682162e+01 ]
avg_reprojection_error: 2.7317193313159532e-01
per_view_reprojection_errors: !!opencv-matrix
   rows: 35
   cols: 1
   dt: f
   data: [ 3.11585248e-01, 2.70595431e-01, 2.86352724e-01,
       3.12916219e-01, 2.53323138e-01, 2.54597694e-01, 2.66269505e-01,
       2.69347519e-01, 2.64548749e-01, 2.69406468e-01, 2.65616447e-01,
       2.60898173e-01, 2.50298768e-01, 3.07076007e-01, 2.58427918e-01,
       2.73020566e-01, 2.43017629e-01, 2.59839147e-01, 2.57417291e-01,
       2.60581434e-01, 2.82334059e-01, 2.84186631e-01, 2.33972371e-01,
       3.14727604e-01, 2.95757264e-01, 2.75137752e-01, 2.09089920e-01,
       2.91144878e-01, 2.01494411e-01, 2.29537964e-01, 1.96766108e-01,
       1.83515012e-01, 3.92196387e-01, 4.17723864e-01, 2.21408263e-01 ]
extrinsic_parameters: !!opencv-matrix
   rows: 35
   cols: 6
   dt: d
   data: [ 1.4020757931808739e-01, -1.4978206447105422e+00,
       -2.6630381140838386e+00, 8.1946438307683536e+01,
       7.3082984624748988e+01, 6.1095055407023347e+02,
       1.0386901064259678e-01, -1.4962637469184645e+00,
       -2.5823925146449187e+00, 1.0944613010360240e+02,
       6.3583338647698469e+01, 6.3410930786901849e+02,
       -5.1723882294775003e-01, 1.2782570740264190e+00,
       2.3552728893606596e+00, 1.1511458685728032e+02,
       5.7378260374439961e+01, 6.4542085963967236e+02,
       -4.4331006157356634e-01, 1.4445529106905999e+00,
       2.5234317612195851e+00, 1.4153655667605247e+02,
       1.9011810776557809e+01, 7.2363034771705793e+02,
       -4.8992490187668097e-01, 1.2629382511910090e+00,
       2.3622518165664865e+00, 8.5209193779612292e+01,
       6.2893914699113338e+01, 6.2697734256628803e+02,
       -8.6117965023459431e-01, 8.3054591881867412e-01,
       1.6472426670500899e+00, 8.4867882685212081e+01,
       5.2753670917877482e+00, 7.2696679613465085e+02,
       -8.6974233064279260e-01, 7.7581974672676068e-01,
       1.5622930744067178e+00, 5.6984316057043792e+01,
       3.6761231468853350e+00, 7.2025937397927373e+02,
       -8.6760569337075555e-01, 7.5447683727763515e-01,
       1.5308709013869746e+00, 1.6643258503733680e+01,
       -2.6883982907169406e+00, 7.1999117397656244e+02,
       -8.7440295878719576e-01, 7.7129323380566384e-01,
       1.5543606445590854e+00, 7.2700985386279910e+01,
       4.2992871016991225e+00, 7.2311683399234698e+02,
       -9.3128816255083235e-01, 6.4270978503653253e-01,
       1.3466862964855975e+00, 3.3449993642992567e+01,
       3.2873095338354781e+00, 7.1600570343345521e+02,
       -9.5579734374222070e-01, 6.1053133358682543e-01,
       1.2938705346385522e+00, 5.2289385807485672e+01,
       6.2800456176596953e+00, 7.1706890032869353e+02,
       -1.0395627203747044e+00, -1.8997652616674421e-01,
       -7.1866314960664007e-02, -9.7326886120201877e+01,
       -1.9141333919085543e+01, 7.2385634640489923e+02,
       -1.0229869631276753e+00, -2.3700307676888629e-01,
       -1.7499580341567758e-01, -7.0038152605832536e+01,
       7.4370340420548287e+00, 6.8582505905130017e+02,
       -1.0365576472071161e+00, -2.8620638543989602e-01,
       -2.0967075239441188e-01, -3.6410928661013877e+01,
       -9.5902395613152027e+00, 7.2176226560760313e+02,
       -1.0378976898388359e+00, -2.7012616591973077e-01,
       -1.6719895240630855e-01, -7.2430085663731901e+01,
       -3.4443618618808948e+01, 7.5477141469740900e+02,
       -7.7967250350047568e-01, -8.1464248381595850e-01,
       -1.1899125318225041e+00, -6.3058479495945029e+01,
       3.5374758962423257e+01, 6.3672818517244264e+02,
       -7.8964922769437007e-01, -8.2715813401835969e-01,
       -1.1551688729701575e+00, -5.4984836758752289e+00,
       2.6464263438245478e+01, 6.6370734222369867e+02,
       -7.6880278101108712e-01, -8.5361230765102403e-01,
       -1.1853701867524991e+00, -4.8248637498475013e+01,
       -6.5165660930517886e+00, 7.0883152937704995e+02,
       -7.7390571370788985e-01, -8.0311759829336882e-01,
       -1.2131837305228961e+00, -9.4052246679600060e+01,
       3.2595819167976721e+01, 6.3720984765142975e+02,
       -7.7896636508317552e-01, -8.1210482140099238e-01,
       -1.1941650733401838e+00, -5.2893062575817105e+01,
       4.6531492740870689e+01, 6.2082433369101636e+02,
       -6.0465409794974212e-01, -1.0251238029652965e+00,
       -1.6028069529555213e+00, -4.1655880051706191e+01,
       5.0553909488402702e+01, 6.1660019518490901e+02,
       -5.9543557962899951e-01, -1.0485708511358414e+00,
       -1.5994230198245687e+00, -9.2233681423780052e+00,
       4.0476075547150984e+01, 6.3916628161220797e+02,
       6.8850956237298630e-02, -1.6293630160442569e+00,
       -2.3857355224718582e+00, 3.8317821183250928e+01,
       3.1460470053967647e+01, 6.3452496635697332e+02,
       -2.6870139278490018e-01, 1.1949295198703771e+00,
       2.5418181388071197e+00, 7.8366916812367734e+01,
       1.5408833239117778e+01, 6.5992943016910624e+02,
       -3.3688508740500400e-01, 1.2757875742336295e+00,
       2.4887814471381438e+00, 7.7320801222035072e+01,
       2.0441875136117574e+01, 6.7176714830078470e+02,
       -2.7723735023944346e-01, 1.3752083697912338e+00,
       2.4829841942258786e+00, 7.8517708309696999e+01,
       2.1998034261425836e+01, 6.6111705733069402e+02,
       -3.6540428674790593e-01, 1.2819572794578038e+00,
       2.7307775602843698e+00, 4.6018163760911314e+01,
       2.9882619680568812e+01, 6.6889345134083294e+02,
       3.2716375454640007e-01, -1.2188947233286063e+00,
       -2.8416512194463022e+00, 5.2692795903863853e+01,
       4.1043836474666328e+01, 6.4518476328646921e+02,
       -9.8786349361266856e-01, -1.0151199581882119e-01,
       -1.1066860275835357e-01, -7.2225578388404372e+01,
       -1.5089105392460388e+01, 7.1136376376437192e+02,
       -9.5780296093236206e-01, -1.0478951653878743e-01,
       -3.1929030457973029e-01, -9.1210600563690377e+01,
       -2.2323212415460894e+01, 7.1265640222500610e+02,
       -7.5745111263498044e-01, -2.3860048919036381e-01,
       -9.0765567760241306e-02, -9.0335568742404035e+01,
       -4.9531235153547492e+01, 7.0170860172749553e+02,
       -8.9881178565901199e-01, -1.1681263218135673e-01,
       1.2261137225625033e-03, -9.4696067958125596e+01,
       -3.4521870205977784e+01, 7.1631093618965349e+02,
       -5.5786188940527082e-01, -8.0559143418462953e-01,
       -1.5993723670324340e+00, -5.1409737803986935e+01,
       3.5201234350970118e+01, 6.2997172592877018e+02,
       -5.8900752065720807e-01, -9.1702003646814156e-01,
       -1.6483022629987707e+00, -3.9239070539114486e+01,
       4.4095380399543075e+01, 6.2605397386594370e+02,
       -8.8519623661188673e-01, 3.6673629436957185e-02,
       -3.2714936197885836e-01, -1.2700882876217365e+02,
       -2.4475336636400534e+01, 6.8794260655285962e+02 ]
