%YAML:1.0
calibration_time: "Wed Dec 26 10:02:58 2018"
nframes: 53
image_width: 2448
image_height: 2048
board_width: 12
board_height: 9
square_size: 1.2510000228881836e+01
flags: 0
camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 4.7044376140907189e+03, 0., 1.2387206678856410e+03, 0.,
       4.7691463862436294e+03, 1.0245150821018608e+03, 0., 0., 1. ]
distortion_coefficients: !!opencv-matrix
   rows: 5
   cols: 1
   dt: d
   data: [ -5.3637301247422706e-02, -2.5903723278328212e+00,
       -8.7588679104234068e-03, 4.6142149059182194e-04,
       2.2321178694957204e+01 ]
avg_reprojection_error: 2.4959563550412592e-01
per_view_reprojection_errors: !!opencv-matrix
   rows: 53
   cols: 1
   dt: f
   data: [ 2.67786890e-01, 2.26183891e-01, 2.94002324e-01,
       3.15557063e-01, 2.80634791e-01, 2.72091895e-01, 2.48806313e-01,
       3.37731034e-01, 1.84527829e-01, 1.90857276e-01, 1.89428076e-01,
       1.88702270e-01, 1.89634725e-01, 1.90387383e-01, 2.84499824e-01,
       2.62799472e-01, 2.71480739e-01, 2.65921205e-01, 2.64062017e-01,
       2.79543519e-01, 2.33828098e-01, 2.42776006e-01, 2.58140832e-01,
       2.18493521e-01, 1.77016616e-01, 2.01551586e-01, 2.16087401e-01,
       1.71270713e-01, 2.51439422e-01, 2.12981775e-01, 1.83981568e-01,
       2.41585523e-01, 1.77509904e-01, 1.99893504e-01, 3.18432570e-01,
       2.08943084e-01, 1.95693418e-01, 2.21352875e-01, 2.31793791e-01,
       3.13829571e-01, 2.70571321e-01, 2.91117758e-01, 2.90327936e-01,
       2.66691655e-01, 2.83116192e-01, 1.96913600e-01, 3.51622701e-01,
       3.28008235e-01, 2.05690786e-01, 2.72103429e-01, 2.34431848e-01,
       3.14137727e-01, 2.03361511e-01 ]
extrinsic_parameters: !!opencv-matrix
   rows: 53
   cols: 6
   dt: d
   data: [ -3.9192331766953359e-02, 1.3297636955104597e+00,
       2.8369295831904697e+00, 8.7451616654372259e+01,
       7.8335277815191162e+01, 4.5669595103766153e+02,
       -1.3040979821588147e-01, 1.3630739371705403e+00,
       2.6731060830982165e+00, 1.0116108788417553e+02,
       -2.4036108144783679e+01, 5.8051881542129956e+02,
       -6.3893525255001637e-01, 8.0233438469822560e-01,
       1.7143269473915734e+00, 1.1602626231571450e+02,
       -4.5113471593733898e+01, 6.1326616665797587e+02,
       -6.2307427528946580e-01, 7.8299115156940813e-01,
       1.7250578269941235e+00, 1.0663491631559754e+02,
       -2.4497100659511744e+01, 5.8589561631011838e+02,
       -7.3672584867697588e-01, 6.5006184010160706e-01,
       1.3871282789237855e+00, 7.6048599432883236e+01,
       -6.2587267701258739e+01, 6.3406015547317247e+02,
       -7.6637151671286063e-01, 6.6460762169078869e-01,
       1.3613506709769017e+00, 7.2513864037568226e+01,
       -9.3409692940878102e+01, 6.7735516351087142e+02,
       -7.6034923845383762e-01, 6.9216615755313171e-01,
       1.4041378366297259e+00, 1.9245082076363026e+01,
       -1.0299929321729036e+02, 6.8890831236285180e+02,
       -7.3627551738178254e-01, 6.0761898608091258e-01,
       1.3390943083032969e+00, 1.8596777139108958e+01,
       -3.8635541325771044e+01, 6.0066910938957892e+02,
       -9.1357974996134095e-01, 2.9866901924439339e-02,
       9.9382581336442802e-02, -2.2403046034143500e+01,
       -6.9906964793789413e+01, 6.4142573757509297e+02,
       -9.0179864024576151e-01, 8.3162077395062040e-02,
       1.9151978266080921e-01, -6.9107785998101264e+01,
       -5.0904348608332647e+01, 6.1643954035403033e+02,
       -9.3193941709326589e-01, 3.7486768884533082e-02,
       9.0543384411369887e-02, -9.9476490654626645e+01,
       -7.3953643975833131e+01, 6.4749480160073210e+02,
       -8.6935150100908110e-01, 2.5142265326633311e-02,
       7.4317215633797451e-02, -8.3208671850848162e+01,
       -1.7325669326216087e+01, 5.7205347493357192e+02,
       -8.9283619641489265e-01, -9.6955393496442714e-03,
       -2.0201454378291203e-03, -7.3765096034589789e+01,
       -4.1596689359253901e+01, 6.0371438306367088e+02,
       -9.3845880787767366e-01, -4.3015891709234561e-02,
       -8.0573177997684736e-02, -8.3909506173907147e+01,
       -8.3785278442711729e+01, 6.6132714258877013e+02,
       -9.1323309629839322e-01, -1.8428760999064944e-01,
       -3.5528531092165089e-01, -1.2090871661663974e+02,
       -5.1626560585918575e+01, 6.1752857893060457e+02,
       -8.7156988124081369e-01, -1.4695810437518542e-01,
       -2.9660091941370825e-01, -9.4982899234187641e+01,
       -1.6176286924190702e+01, 5.7167626639618811e+02,
       -9.0241070122795952e-01, -1.8486116579642337e-01,
       -3.6424667096140961e-01, -1.1800248975311762e+02,
       -3.7842664713014535e+01, 5.9995302604375718e+02,
       -6.8782008078373102e-01, -7.1064797493572496e-01,
       -1.4670730668651595e+00, -6.4823675575164344e+01,
       2.6194047508884118e+01, 5.1987439260367637e+02,
       -6.5832901358547380e-01, -6.8803832986646252e-01,
       -1.4965903765186594e+00, -6.0849737184220835e+01,
       5.8630682757551590e+01, 4.8473029189275661e+02,
       -7.0713215044148714e-01, -7.1361271249288805e-01,
       -1.4439740875978830e+00, -2.2651285517055598e+01,
       1.0337005450896710e+01, 5.3878543756172019e+02,
       -6.9101174588754111e-01, -7.3588302208873269e-01,
       -1.4841354242790288e+00, -1.0886387919581618e+02,
       5.8379454231253485e+00, 5.4276318028792423e+02,
       -6.7195362575707329e-01, -6.8747672163378548e-01,
       -1.4795460793625665e+00, -3.1727962884784784e+01,
       5.5603890540441668e+01, 4.8767751058077926e+02,
       -7.0050392406354722e-01, -7.3158961829198454e-01,
       -1.4715648731089490e+00, -1.5469038922271077e+01,
       9.2168378721841187e+00, 5.4014843414156769e+02,
       -7.2198877453778831e-01, -7.0274651224954254e-01,
       -1.3983809367173583e+00, -9.5899807495399855e+01,
       -1.5907708816730484e+00, 5.5209779013517493e+02,
       -1.3464954369272994e-01, -1.2262909727043567e+00,
       -2.6481420836648795e+00, 3.6810559953910335e+01,
       5.0889161583565041e+01, 4.9318629195528302e+02,
       -6.1960395338969153e-02, 1.3042572993976658e+00,
       2.7903444926208949e+00, 3.6427980622778335e+01,
       2.5383898024559599e+01, 5.2371304391892261e+02,
       8.8429473376557943e-03, -1.3136359255879977e+00,
       -2.8496494207577343e+00, 9.8305037233888598e+01,
       4.7201644753711641e+01, 4.9818785020209174e+02,
       -3.9832501283394724e-02, 1.3890079262213377e+00,
       2.7962574387835923e+00, 1.0457055038748152e+02,
       -1.2346605161068767e+01, 5.6963749858392418e+02,
       -4.1130303157676969e-02, 1.3991712066494908e+00,
       2.8005675213475913e+00, 1.5972885779277053e+01,
       -2.1243796128676014e+01, 5.7967505687609173e+02,
       -4.3213245257164148e-02, 1.1339259169961133e+00,
       2.9035908462171194e+00, 6.2519876527799845e+01,
       -3.6216330662459968e+00, 5.5266658500788037e+02,
       1.0534614010768384e-01, 1.3561654154785745e+00,
       2.7783814195695093e+00, 5.5338434834421832e+01,
       -1.6735385351720851e+01, 5.4689403141407718e+02,
       1.3496801646567533e-01, -1.3112094215731471e+00,
       -2.7840538873288909e+00, 5.4503344564604383e+01,
       7.5552146630094441e+00, 5.3672341623831551e+02,
       -5.1989580262833304e-02, 1.5379754715480343e+00,
       2.6912196880067483e+00, 6.6398994663214822e+01,
       4.6408619950494199e+00, 5.1775132972429469e+02,
       -3.4962392675922548e-04, -9.4744291561701710e-01,
       -2.9766935511413073e+00, 5.4802886158401044e+01,
       5.9417940062253765e+00, 5.3647914745771652e+02,
       2.9178596324044354e-01, -1.2870279735135879e+00,
       -2.7930952756125720e+00, 5.3422652785347211e+01,
       9.4612357348252409e+00, 5.2867105882113628e+02,
       -2.2593945725836198e-01, 1.0358877215757727e+00,
       2.6101977375700645e+00, 5.2939894482717968e+01,
       -8.8159602885030992e+00, 5.5499649358192721e+02,
       -1.2683024491677164e-01, 1.1465878880773082e+00,
       2.5148578291133941e+00, 4.6956112393704267e+01,
       -1.7071552591886164e+01, 5.4982487530190315e+02,
       -2.3622972683069521e-01, 1.3493723125360901e+00,
       2.7668416565706093e+00, 6.1701650693968453e+01,
       4.0254064263876330e+00, 5.4149116958423360e+02,
       -3.1994515744687729e-01, 1.3202037730537184e+00,
       2.2787513584547763e+00, 5.5641883197553945e+01,
       -2.7679876972464793e+01, 5.6070523800348928e+02,
       -6.4673910145860436e-01, 5.7900412418056768e-01,
       1.4048497105697304e+00, 2.7982823610060898e+01,
       -7.2947639368400999e+01, 6.1822207643050604e+02,
       -6.3002631608149429e-01, 7.6552296920341945e-01,
       1.3833651960887621e+00, 3.9471908844344973e+01,
       -7.1416693075333626e+01, 6.1882781656901739e+02,
       -7.9553855254356864e-01, 6.2891829625470408e-01,
       1.6533911146745397e+00, 1.3794773472465891e+01,
       -5.9051025813783845e+01, 6.2248088496613252e+02,
       -9.1081698378419029e-01, 5.4265636265116712e-01,
       1.7372750074120915e+00, 2.2967555275185724e+01,
       -5.8239175868085191e+01, 6.1920041984230613e+02,
       -8.4604512833788703e-01, 5.0545927610257613e-01,
       1.3500308733157198e+00, 9.1977858005336017e+00,
       -6.2456794033330290e+01, 6.2071239341800037e+02,
       -6.4321381756808849e-01, 6.9366070707698524e-01,
       1.2651862256000204e+00, 2.6969987807805325e+01,
       -7.3665210752666923e+01, 6.1874997569781897e+02,
       -6.5056552902773823e-01, 6.7286834161012679e-02,
       1.3352550810991679e-01, -7.8589039930420867e+01,
       -8.7956616727254655e+01, 6.0768958287606210e+02,
       -8.0633241730308003e-01, -6.7696470611816814e-02,
       2.7471570238892279e-01, -9.2892575309371807e+01,
       -9.4198605418315282e+01, 6.0731016186089971e+02,
       -8.6213591856394323e-01, 6.2763264378850551e-04,
       2.2334566828644220e-01, -9.6689833436412059e+01,
       -7.6638860893569429e+01, 6.1923290667073343e+02,
       -9.1712464119833870e-01, 6.8589537615862034e-02,
       -3.4604434471326460e-02, -9.8952556792046764e+01,
       -6.6596802935631700e+01, 6.3011683274168672e+02,
       -5.9429439995577116e-01, -6.4945813087669546e-01,
       -1.5541591883763304e+00, -5.3127791263673323e+01,
       3.9478064488268821e+01, 5.0120651866961845e+02,
       -6.0789047914724825e-01, -7.7285691362821274e-01,
       -1.3197570279728361e+00, -7.3892489206731881e+01,
       4.9487940755001265e+00, 5.1375046586790586e+02,
       -5.0853693181236137e-01, -8.5772870616004449e-01,
       -1.2007065261811414e+00, -6.0545000617966686e+01,
       -9.5116476957735170e+00, 4.9676273964245092e+02,
       -2.3144858224495152e-02, 1.3971614902110019e+00,
       2.7762361751668108e+00, 7.6749707296424461e+01,
       8.0275235556868111e+01, 4.9260071971844951e+02 ]
